# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KEs1ypz-qjLuKzF8_dek43qycNxKLApm
"""

import streamlit as st
import pandas as pd
import pickle

# Load trained model
with open("credit_model.pkl", "rb") as f:
    model = pickle.load(f)

st.set_page_config(page_title="Credit Card Fraud Detection")

st.title("💳 Credit Card Fraud Detection")
st.write("Enter transaction details")

# Input fields (MUST match training data)
input_data = {}

# Time feature (IMPORTANT)
input_data["Time"] = st.number_input("Time", min_value=0.0, value=0.0)

# V1 to V28
for i in range(1, 29):
    input_data[f"V{i}"] = st.number_input(
        f"V{i}", value=0.0, format="%.6f"
    )

# Amount
input_data["Amount"] = st.number_input("Amount", min_value=0.0, value=0.0)

# Convert to DataFrame with correct column order
input_df = pd.DataFrame([input_data])

# Ensure correct feature order
input_df = input_df[model.feature_names_in_]

# Prediction
if st.button("Check Transaction"):
    prediction = model.predict(input_df)

    if prediction[0] == 1:
        st.error("⚠️ Fraudulent Transaction Detected")
    else:
        st.success("✅ Legitimate Transaction")