# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqSctKoeWV6brCYAHkIKYFpFXssLLy1O
"""

import streamlit as st
import pandas as pd
import pickle

# Load trained model
with open("credit_model.pkl", "rb") as f:
    model = pickle.load(f)

st.set_page_config(page_title="Credit Card Fraud Detection")

st.title("💳 Credit Card Fraud Detection")
st.write("Enter transaction details to check if it is fraudulent")

# Collect inputs
input_data = {}

for i in range(1, 29):
    input_data[f"V{i}"] = st.number_input(
        f"V{i}", value=0.0, format="%.6f"
    )

amount = st.number_input("Amount", min_value=0.0, value=0.0)
input_data["Amount"] = amount

# Convert input to DataFrame
input_df = pd.DataFrame([input_data])

# Prediction
if st.button("Check Transaction"):
    prediction = model.predict(input_df)

    if prediction[0] == 1:
        st.error("⚠️ Fraudulent Transaction Detected")
    else:
        st.success("✅ Legitimate Transaction")